### PR TITLE
Add Douglas C-47 tow plane

### PR DESCRIPTION
**Pull request by wlbragg**
This is just the C-47, not tied to the route creation menu yet. I didn't study how to tie it in yet.
Also there are 3 extra engine sounds, I thought the one I chose was best, but never tested the other  3. You may like another one better.

I wasn't sure about all the specs in aircraft.nas. I couldn't find "stall speed".
I found [this](https://www.docdroid.com/HOqlW3c/douglas-c-47-skytrain-pilot-training-manual-pdf#page=54) little bit of info, and of course there is the [wiki](https://en.wikipedia.org/wiki/Douglas_C-47_Skytrain).

If you want me to tie it in to the route portion I can. Or you can if you prefer.

On the forum, I mentioned the ASK 21 menu under Aerotow Configuration for another idea for an addition to the addon. It is user defined rope configuration. I think that would be a great addition to this as well. If your not interested in adding it yourself , maybe I could add it at some point.

One other idea I thought of, you may have already thought of this yourself, is for the user to be able to save the tow routes they create. In the case of the Airspeed Horsa, I would make a D-Day route that tows the aircraft on the same route they used on D-Day and then save it.. Of course people could save and trade individual airport routes used in the real world at glider clubs. Like the one that gave me the idea of doing routes at CL35. Just a thought for future upgrades. I have example code for saving and loading aircraft position data in both the c172p and the Cub. I thought it was important to be able to save trip data for bush trips where there was not an airport, but only a  remote bush location or remote lake somewhere.

Let me know if you want anything else or for me to do anything different. Or if you want my help to maybe create some of these ideas.

### CODE REVIEW

**Comment by PlayeRom** [comment]
Thanks!

I think the sound you've chosen is the best.

I don't use "stall speed", it's not needed, it's just in the comments for information.

For tie C-47 in to the route it's only add the "name" value to the combo box, so no problem, I will do it.

About rope configuration, do you mean copy the solution from ASK 21 and move it to the add-on? I wonder what for, but I guess you want this to be available to any glider that doesn't support it, right?

Saving and loading routes is a good idea.

At the moment, it is rather impossible to take off without an airport, although in fact I have never tested it, but when I'm creating a flight plan for an AI plane, I base on the data of airport and the runway. But I think it can be reworked by reading the glider heading and geographic position.

I installed Airspeed Horsa from official hangar and I see a problem there. This glider has build in dragger robot which is loaded by press Ctrl-o, which means that Ctrl-o doesn't hook to plane from add-on. Besides, the dragger robot after loading, stands still and does not take off, I do not know how to start with towing at all, am I doing something wrong?

**Comment by wlbragg** [comment]
I have a local version of the Airspeed Horsa, I corrected the towing bindings. I'll talk to Helijah and see if he'll let me make a change on the one in FG add-on so it works by default.

**Comment by wlbragg** [comment]
>About rope configuration, do you mean copy the solution from ASK 21 and move it to the add-on? I wonder what for, but I guess you want this to be available to any glider that doesn't support it, right?

Yes, I think there's more that don't have it available with the aircraft then that do.

As far as saving the flight plans. It's more about just being able to save them per airport, and not really about outside of an airport, I didn't think of that. My example was that the bush planes I make, they do land outside airports and so I wanted to be able to save for that. To pick up where I left off. But not necessarily for the toe planes, The thought was mainly just to save a flight plan at an airport.

**Comment by PlayeRom** [comment]
OK, I think I can add a rope configuration.

I just added function to save/load to the file the configuration of "Aerotow Route" dialog. I'm not sure if this is what you are writing about?

I think we should move this discussion to separate "Issues" :)

**Pull request merged**
