### PR TITLE
Remove unused sounds, interior and exterior sound

### PR DESCRIPTION
**Pull request by wlbragg**
I uploaded Version 1..5.0 to addons repository without this sound change. Next version change you do, I can push that to addons incorporating these changes, or we both can just backport this commit to 1.5.0. However you want to do it.

### CODE REVIEW

**Comment by wlbragg** [comment]
What about saving thermal locations? You would then theoretically be able to set a flight plan, drop thermals at the appropriate places along the route,. Save all that, and start out the next time without having to do a thing except load.

I sent a PM to Helijah about the AIrspeed Horsa. Hopefully I will hear back from him soon.

**Comment by PlayeRom** [comment]
Thanks!

Regarding saving thermals, any idea how to handle this in the gui? The route is determined by turning points as a change of heading and distance, but how to add the thermals there? By giving geographical coordinates? In my opinion giving geographical coordinates is inconvenient for users. The easiest way is to add the thermals option, but always in the same place where the waypoint is, is it enough?

BTW I like the way of routing for pushback in some airliners, where the view changes to top view and the user clicks on the terrain indicating the pushback route points. I've been trying to adapt this for routing (it could also be for thermals), but there's the problem that I have to set the camera very high to show the view around the airport and beyond. And this is where the fog that starts to obscure the ground already comes in. Or maybe I could use the keyboard arrows to pan the camera along the ground, maybe then I would not have to set the camera that high and the fog would not interfere.

**Comment by wlbragg** [comment]
>Or maybe I could use the keyboard arrows to pan the camera along the ground

Like the old "SLEW" we used to have, where you could slew the aircraft across the terrain. Only do that to the view instead. Could work. 

Or to keep it simple and not have to write much more code you could use the existing "Add thermal", and just keep track of them in the session and give the user a "save thermals" for it so they can save before exiting.

A variation of that is to set a flag (gui choice) where instead of out ahead of you it drops the thermal at your aircraft_pos. Then just keep track of them in the session and give the user a "save thermals" for it so they can save before exiting.

**Comment by wlbragg** [comment]
I just used the Aerotow route in the addon, you could use the same interface for dropping the thermals. Just make it so each entry is a new thermal.

It goes something like this first entry... 
heading 23 / distance 2000 m
heading 23.4 / distance 2005 m
heading 23.9 / distance 2013 m
etc.

I think using Phi map or any other map that has a scale on it you could drop thermal close enough to where you want them. There would be a small amount of randomness because of possible distance to target. But it would be the easiest for you. Then just save and load it like you save and load the routes. That way you have the thermals in advance of ever making that first flight.

**Comment by wlbragg** [comment]
Even...

heading 23 / distance 2000 m / strength 16 / diameter 4000 / Height MSL 9000
heading 23.4 / distance 2005 m / strength 15 / diameter 3000 / Height MSL 8500 
heading 23.9 / distance 2013 m / strength 19 / diameter 4000 / Height MSL 10000

It requires the user to have to think a bit, but anyone doing gliders should be halfway intelligent anyway, enough to plot points on a map. These points are all from the aircraft parked position.
Or you could do it sequentially such as the flight plan. I think from the parked position would be the easiest all the way around.

**Comment by wlbragg** [comment]
Can we not change the altitude in the "route manager"? Did that present some issue? Or is it you figured there was really no need? I guess for regular gliding you have distance X @ VS per second calculates the height, right?

For the Horsa d-day flights, I need altitude changes. Actually they were anywhere from a constant 700 AGL to a variable AGL. 

Just adding the ability to set altitude in the route would be enough. But that brings up another interesting concept, dynamic user controlled tow plane., once a basic route is established, the user could change (override) any waypoint for direction, distance and altitude. Just a thought.

Also, it would be nice if users would post any routs they create for specific glider club courses or locations. We could then potentially add them to a "next release. For now I am hand editing the d-day flight path. I can provide it when finished as a flight plan that comes with the addon.

**Comment by wlbragg** [comment]
I thought they fixed the issue with the load/save window being hidden behind the main fg window. It took me a while to figure out why my fg was froze. The save window helper was not the focused window, it was hidden. This was in Windows 10.

**Comment by wlbragg** [comment]
One more thing, I guess editing the flight plan doesn't help with the altitude. It still calculates its own VS based on distance.

**Comment by PlayeRom** [comment]
Each time you call a tow plane, a scenario with a flight plan is generated and loaded into the FG, so editing the file with flight plan does not make sense, because the changes will be overwritten. And after calling the plane, it also makes no sense, because everything has already been loaded.

I did not add altitude editing so as not to inconvenience the user who could set it unrealistically with some steep climb, so when flying, the plane simply always increases altitude with a predetermined vertical speed, depending on the plane.

For a dynamic change in altitude, and for the flight plan in general, I have to get rid of loading the flight plan from the XML file I'm based on. I raised the topic on the mailing group https://sourceforge.net/p/flightgear/mailman/flightgear-devel/thread/From_killaccount%40cox.net_Wed_Aug_17_04%3A01%3A50_2022/#msg37694479 and maybe James will implement dynamic adding of the route via Nasal API, then it would be possible and would eliminate the need to use `--data`.

**Comment by wlbragg** [comment]
@PlayeRom 

>I did not add altitude editing so as not to inconvenience the user who could set it unrealistically with some steep climb, so when flying, the plane simply always increases altitude with a predetermined vertical speed, depending on the plane.

I think we need the ability to edit altitude, or at the least a user defined "max" altitude limit.

A real glider club location someone wants to practice at may have a set route, including altitude changes. But that could theoretically be achieved by the route distance, so the user can still adjust route length to achieve the desired altitude at target.

But specific tow missions, such as the Airspeed Horsa, end up at +70000 agl by the end of the tow mission. They typically towed from 200-2000agl all the way from Great Britain to France.

You could offer a "Max Altitude" input field, the user could then input a number that would clamp the altitude not to exceed that number. If blank or 0, then it is ignored. That would work for my purposes.

**Comment by PlayeRom** [comment]
Adding "Max Altitude" is a good idea and easy to implement, I'll take care of it in my free time.

**Comment by wlbragg** [comment]
Thanks, that will be sufficient. I would have tried to do it myself, but I hadn't looked at that part of the code yet. I figured it would be a simple addition for you to make. I appreciate it!

**Pull request merged**
